# -*- coding: utf-8 -*-
"""Top10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Wqqamp6tbAOSQr0KKSEjdCBrNeCuYldd
"""

import re
import unicodedata
from typing import Dict, List, Optional, Set


MAX_LIVES = 3


def normalize(text: str) -> str:
    text = unicodedata.normalize("NFKD", text)
    text = text.encode("ascii", "ignore").decode("ascii")
    text = text.lower().strip()
    text = text.replace("&", " and ")
    text = re.sub(r"[^\w\s]", " ", text)
    text = re.sub(r"\s+", " ", text)
    return text


CATEGORIES: List[Dict] = [
    {
        "id": 1,
        "title": "Top 10 biggest cities in size",
        "aliases": [
            "biggest cities in size",
            "largest cities by size",
            "largest cities by area",
            "biggest cities area",
            "cities in size",
            "city size",
        ],
        "ranking_note": "Urban areas by built-up land area (not city proper).",
        "answers": [
            {"name": "Greater Brisbane", "aliases": ["Brisbane"]},
            {"name": "Greater Sydney", "aliases": ["Sydney"]},
            {"name": "New York City", "aliases": ["New York", "NYC"]},
            {"name": "Guangzhou-Shenzhen", "aliases": ["Guangzhou", "Shenzhen", "Guangzhou Shenzhen"]},
            {"name": "Greater Melbourne", "aliases": ["Melbourne"]},
            {"name": "Shanghai-Changzhou", "aliases": ["Shanghai", "Changzhou", "Shanghai Changzhou"]},
            {"name": "Boston-Providence", "aliases": ["Boston", "Providence", "Boston Providence"]},
            {"name": "Tokyo-Yokohama", "aliases": ["Tokyo", "Yokohama", "Tokyo Yokohama"]},
            {"name": "Atlanta", "aliases": []},
            {"name": "Greater Los Angeles", "aliases": ["Los Angeles", "LA"]},
        ],
        "sources": [
            {
                "title": "Wikipedia — List of largest cities by area (Urban areas table, based on Demographia World Urban Areas)",
                "url": "https://en.wikipedia.org/wiki/List_of_largest_cities_by_area",
            }
        ],
        "source_note": "This list uses urban areas/conurbations with at least 5,000 km² of built-up land area, so some entries are combined metro areas rather than city proper."
    },
    {
        "id": 2,
        "title": "Top 10 biggest cities in population",
        "aliases": [
            "biggest cities in population",
            "largest cities by population",
            "most populated cities",
            "cities population",
            "city population",
        ],
        "ranking_note": "Urban area population estimates for 2025 (not city proper).",
        "answers": [
            {"name": "Jakarta", "aliases": []},
            {"name": "Dhaka", "aliases": []},
            {"name": "Tokyo", "aliases": ["Tōkyō"]},
            {"name": "New Delhi", "aliases": ["Delhi"]},
            {"name": "Shanghai", "aliases": []},
            {"name": "Guangzhou", "aliases": []},
            {"name": "Cairo", "aliases": []},
            {"name": "Manila", "aliases": []},
            {"name": "Kolkata", "aliases": ["Calcutta"]},
            {"name": "Seoul", "aliases": []},
        ],
        "sources": [
            {
                "title": "Worldometer — Largest Cities by Population in the World (2025)",
                "url": "https://www.worldometers.info/population/largest-cities-in-the-world/",
            }
        ],
        "source_note": "This source ranks urban areas/agglomerations, not city proper administrative limits."
    },
    {
        "id": 3,
        "title": "Top 10 biggest countries in size",
        "aliases": [
            "biggest countries in size",
            "largest countries by area",
            "biggest countries area",
            "countries in size",
            "largest countries",
        ],
        "ranking_note": "Countries ranked by total area.",
        "answers": [
            {"name": "Russia", "aliases": ["Russian Federation"]},
            {"name": "Canada", "aliases": []},
            {"name": "China", "aliases": []},
            {"name": "United States", "aliases": ["USA", "US", "United States of America", "America"]},
            {"name": "Brazil", "aliases": []},
            {"name": "Australia", "aliases": []},
            {"name": "India", "aliases": []},
            {"name": "Argentina", "aliases": []},
            {"name": "Kazakhstan", "aliases": []},
            {"name": "Algeria", "aliases": []},
        ],
        "sources": [
            {
                "title": "Worldometer — Largest Countries in the World by Area",
                "url": "https://www.worldometers.info/geography/largest-countries-in-the-world/",
            }
        ],
        "source_note": "Total area is used."
    },
    {
        "id": 4,
        "title": "Top 10 biggest countries in population",
        "aliases": [
            "biggest countries in population",
            "largest countries by population",
            "most populous countries",
            "countries population",
            "country population",
        ],
        "ranking_note": "Countries by population at the start of 2025.",
        "answers": [
            {"name": "India", "aliases": []},
            {"name": "China", "aliases": []},
            {"name": "United States", "aliases": ["USA", "US", "United States of America", "America"]},
            {"name": "Indonesia", "aliases": []},
            {"name": "Pakistan", "aliases": []},
            {"name": "Nigeria", "aliases": []},
            {"name": "Brazil", "aliases": []},
            {"name": "Bangladesh", "aliases": []},
            {"name": "Russia", "aliases": ["Russian Federation"]},
            {"name": "Ethiopia", "aliases": []},
        ],
        "sources": [
            {
                "title": "BusinessDay — Top 10 most populous countries in the world (2025), citing Worldometer",
                "url": "https://businessday.ng/world/article/top-10-most-populous-countries-in-the-world-2025/",
            },
            {
                "title": "Worldometer — Population by Country",
                "url": "https://www.worldometers.info/world-population/population-by-country/",
            }
        ],
        "source_note": "This game uses a fixed 2025 snapshot."
    },
    {
        "id": 5,
        "title": "Top 10 cuisines",
        "aliases": [
            "top cuisines",
            "best cuisines",
            "cuisines",
            "top 10 cuisines",
            "best food countries",
        ],
        "ranking_note": "TasteAtlas audience-rating ranking of cuisines.",
        "answers": [
            {"name": "Italian cuisine", "aliases": ["Italy", "Italian"]},
            {"name": "Greek cuisine", "aliases": ["Greece", "Greek"]},
            {"name": "Peruvian cuisine", "aliases": ["Peru", "Peruvian"]},
            {"name": "Portuguese cuisine", "aliases": ["Portugal", "Portuguese"]},
            {"name": "Spanish cuisine", "aliases": ["Spain", "Spanish"]},
            {"name": "Japanese cuisine", "aliases": ["Japan", "Japanese"]},
            {"name": "Turkish cuisine", "aliases": ["Turkey", "Türkiye", "Turkiye", "Turkish"]},
            {"name": "Chinese cuisine", "aliases": ["China", "Chinese"]},
            {"name": "French cuisine", "aliases": ["France", "French"]},
            {"name": "Indonesian cuisine", "aliases": ["Indonesia", "Indonesian"]},
        ],
        "sources": [
            {
                "title": "TasteAtlas — 100 Best Cuisines",
                "url": "https://www.tasteatlas.com/best/cuisines",
            },
            {
                "title": "TasteAtlas Awards",
                "url": "https://www.tasteatlas.com/awards",
            }
        ],
        "source_note": "This category is inherently subjective because it depends on TasteAtlas audience ratings."
    },
    {
        "id": 6,
        "title": "Top 10 countries with the most tourists",
        "aliases": [
            "countries with the most tourists",
            "most visited countries",
            "tourist countries",
            "tourism",
            "tourists",
        ],
        "ranking_note": "International tourist arrivals.",
        "answers": [
            {"name": "France", "aliases": []},
            {"name": "Spain", "aliases": []},
            {"name": "United States", "aliases": ["USA", "US", "United States of America", "America"]},
            {"name": "Turkey", "aliases": ["Türkiye", "Turkiye"]},
            {"name": "Italy", "aliases": []},
            {"name": "Mexico", "aliases": []},
            {"name": "United Kingdom", "aliases": ["UK", "Britain", "Great Britain"]},
            {"name": "Germany", "aliases": []},
            {"name": "Japan", "aliases": []},
            {"name": "Greece", "aliases": []},
        ],
        "sources": [
            {
                "title": "Wikipedia — World Tourism rankings (compiled by UN Tourism)",
                "url": "https://en.wikipedia.org/wiki/World_Tourism_rankings",
            }
        ],
        "source_note": "You asked for 2025, but the latest complete public country ranking available in a clean table when this game was built was the UN Tourism 2024 arrivals ranking. So this category uses that official 2024 snapshot."
    },
    {
        "id": 7,
        "title": "Top 10 countries with the most CO2 emissions",
        "aliases": [
            "countries with the most co2 emissions",
            "top co2 emitters",
            "co2 emissions countries",
            "annual co2 emissions",
            "co2 emissions",
        ],
        "ranking_note": "Annual country CO₂ emissions.",
        "answers": [
            {"name": "China", "aliases": []},
            {"name": "United States", "aliases": ["USA", "US", "United States of America", "America"]},
            {"name": "India", "aliases": []},
            {"name": "Russia", "aliases": ["Russian Federation"]},
            {"name": "Japan", "aliases": []},
            {"name": "Iran", "aliases": ["Islamic Republic of Iran"]},
            {"name": "Indonesia", "aliases": []},
            {"name": "Saudi Arabia", "aliases": []},
            {"name": "Germany", "aliases": []},
            {"name": "South Korea", "aliases": ["Korea", "Republic of Korea"]},
        ],
        "sources": [
            {
                "title": "World Population Review — CO₂ Emissions by Country 2026 (country table uses 2023 data)",
                "url": "https://worldpopulationreview.com/country-rankings/co2-emissions-by-country",
            }
        ],
        "source_note": "You asked for 2025, but the latest complete public annual country table I used here was for 2023. So this game uses that latest complete annual ranking instead of an incomplete live-year estimate."
    },
    {
        "id": 8,
        "title": "Top 10 countries with the most CO2 emissions of all time",
        "aliases": [
            "countries with the most co2 emissions all time",
            "historical co2 emissions",
            "cumulative co2 emissions",
            "all time co2",
        ],
        "ranking_note": "Cumulative CO₂ emissions since 1750.",
        "answers": [
            {"name": "United States", "aliases": ["USA", "US", "United States of America", "America"]},
            {"name": "China", "aliases": []},
            {"name": "Russia", "aliases": ["Russian Federation"]},
            {"name": "Germany", "aliases": []},
            {"name": "United Kingdom", "aliases": ["UK", "Britain", "Great Britain"]},
            {"name": "Japan", "aliases": []},
            {"name": "India", "aliases": []},
            {"name": "France", "aliases": []},
            {"name": "Canada", "aliases": []},
            {"name": "Ukraine", "aliases": []},
        ],
        "sources": [
            {
                "title": "Union of Concerned Scientists — Each Country's Share of CO2 Emissions",
                "url": "https://www.ucs.org/resources/each-countrys-share-co2-emissions",
            }
        ],
        "source_note": "This ranking uses cumulative CO₂ emissions since 1750 from fossil fuels and cement only."
    },
    {
        "id": 9,
        "title": "Top 10 happiest countries in the world",
        "aliases": [
            "happiest countries",
            "happy countries",
            "world happiness",
            "happiness ranking",
        ],
        "ranking_note": "World Happiness Report 2025 ranking.",
        "answers": [
            {"name": "Finland", "aliases": []},
            {"name": "Denmark", "aliases": []},
            {"name": "Iceland", "aliases": []},
            {"name": "Sweden", "aliases": []},
            {"name": "Netherlands", "aliases": ["Holland"]},
            {"name": "Costa Rica", "aliases": []},
            {"name": "Norway", "aliases": []},
            {"name": "Israel", "aliases": []},
            {"name": "Luxembourg", "aliases": []},
            {"name": "Mexico", "aliases": []},
        ],
        "sources": [
            {
                "title": "World Happiness Report 2025",
                "url": "https://www.worldhappiness.report/ed/2025/",
            },
            {
                "title": "Happier Lives Institute — The top 25 happiest countries in 2025",
                "url": "https://www.happierlivesinstitute.org/2025/03/20/the-top-25-happiest-countries-in-2025-plus-our-four-favourite-findings-from-the-2025-world-happiness-report/",
            }
        ],
        "source_note": "This game uses the 2025 report ranking."
    },
    {
        "id": 10,
        "title": "Top 10 biggest countries in Europe in size",
        "aliases": [
            "biggest countries in europe in size",
            "largest european countries by area",
            "europe countries area",
            "largest countries in europe",
            "europe area",
        ],
        "ranking_note": "European countries ranked by area in Europe.",
        "answers": [
            {"name": "Russia", "aliases": ["Russian Federation"]},
            {"name": "Ukraine", "aliases": []},
            {"name": "France", "aliases": []},
            {"name": "Spain", "aliases": []},
            {"name": "Sweden", "aliases": []},
            {"name": "Germany", "aliases": []},
            {"name": "Finland", "aliases": []},
            {"name": "Norway", "aliases": []},
            {"name": "Poland", "aliases": []},
            {"name": "Italy", "aliases": []},
        ],
        "sources": [
            {
                "title": "WorldAtlas — The Largest Countries in Europe",
                "url": "https://www.worldatlas.com/geography/the-largest-countries-in-europe.html",
            },
            {
                "title": "Wikipedia — List of European countries by area",
                "url": "https://en.wikipedia.org/wiki/List_of_European_countries_by_area",
            }
        ],
        "source_note": "For transcontinental countries, the European-area interpretation is used."
    },
    {
        "id": 11,
        "title": "Top 10 biggest cities in Europe in population",
        "aliases": [
            "biggest cities in europe in population",
            "largest european cities by population",
            "europe cities population",
            "european cities population",
        ],
        "ranking_note": "European cities by population.",
        "answers": [
            {"name": "Moscow", "aliases": []},
            {"name": "Paris", "aliases": []},
            {"name": "London", "aliases": []},
            {"name": "Madrid", "aliases": []},
            {"name": "Barcelona", "aliases": []},
            {"name": "Saint Petersburg", "aliases": ["St Petersburg", "St. Petersburg", "Saint-Petersburg"]},
            {"name": "Rome", "aliases": []},
            {"name": "Berlin", "aliases": []},
            {"name": "Milan", "aliases": []},
            {"name": "Athens", "aliases": []},
        ],
        "sources": [
            {
                "title": "World Population Review — Europe Cities by Population 2026",
                "url": "https://worldpopulationreview.com/cities/continent/europe",
            }
        ],
        "source_note": "This game uses the ranked city list shown on the page."
    },
    {
        "id": 12,
        "title": "Top 10 biggest countries in Europe in population",
        "aliases": [
            "biggest countries in europe in population",
            "most populous countries in europe",
            "europe countries population",
            "european countries population",
        ],
        "ranking_note": "European countries by population.",
        "answers": [
            {"name": "Russia", "aliases": ["Russian Federation"]},
            {"name": "Germany", "aliases": []},
            {"name": "United Kingdom", "aliases": ["UK", "Britain", "Great Britain"]},
            {"name": "France", "aliases": []},
            {"name": "Italy", "aliases": []},
            {"name": "Spain", "aliases": []},
            {"name": "Ukraine", "aliases": []},
            {"name": "Poland", "aliases": []},
            {"name": "Romania", "aliases": []},
            {"name": "Netherlands", "aliases": ["Holland"]},
        ],
        "sources": [
            {
                "title": "Worldometer — Countries in Europe by Population",
                "url": "https://www.worldometers.info/population/countries-in-europe-by-population/",
            }
        ],
        "source_note": "This game uses the page snapshot available when the list was built."
    },
    {
        "id": 13,
        "title": "Top 10 countries by GDP",
        "aliases": [
            "countries by gdp",
            "richest countries by gdp",
            "biggest economies",
            "most rich countries",
            "gdp",
        ],
        "ranking_note": "Nominal GDP ranking.",
        "answers": [
            {"name": "United States", "aliases": ["USA", "US", "United States of America", "America"]},
            {"name": "China", "aliases": []},
            {"name": "Germany", "aliases": []},
            {"name": "India", "aliases": []},
            {"name": "Japan", "aliases": []},
            {"name": "United Kingdom", "aliases": ["UK", "Britain", "Great Britain"]},
            {"name": "France", "aliases": []},
            {"name": "Italy", "aliases": []},
            {"name": "Russia", "aliases": ["Russian Federation"]},
            {"name": "Canada", "aliases": []},
        ],
        "sources": [
            {
                "title": "Wikipedia — List of countries by GDP (nominal), using IMF projections table",
                "url": "https://en.wikipedia.org/wiki/List_of_countries_by_GDP_(nominal)",
            }
        ],
        "source_note": "This game uses the nominal GDP ranking shown in the IMF-based table."
    },
    {
        "id": 14,
        "title": "Top 10 countries with offshore wind capacity",
        "aliases": [
            "offshore wind capacity",
            "countries with offshore wind",
            "offshore wind",
            "top offshore wind countries",
        ],
        "ranking_note": "Cumulative installed offshore wind capacity.",
        "answers": [
            {"name": "China", "aliases": []},
            {"name": "United Kingdom", "aliases": ["UK", "Britain", "Great Britain"]},
            {"name": "Germany", "aliases": []},
            {"name": "Netherlands", "aliases": ["Holland"]},
            {"name": "Denmark", "aliases": []},
            {"name": "Belgium", "aliases": []},
            {"name": "Taiwan", "aliases": []},
            {"name": "France", "aliases": []},
            {"name": "Vietnam", "aliases": []},
            {"name": "Japan", "aliases": []},
        ],
        "sources": [
            {
                "title": "Wikipedia — Offshore wind power by country",
                "url": "https://en.wikipedia.org/wiki/Offshore_wind_power",
            }
        ],
        "source_note": "This game uses the cumulative installed offshore wind capacity table for year-end 2024."
    },
    {
        "id": 15,
        "title": "Top 10 countries with onshore wind capacity",
        "aliases": [
            "onshore wind capacity",
            "countries with onshore wind",
            "onshore wind",
            "top onshore wind countries",
        ],
        "ranking_note": "Approximate onshore capacity = total wind capacity minus offshore wind capacity.",
        "answers": [
            {"name": "China", "aliases": []},
            {"name": "United States", "aliases": ["USA", "US", "United States of America", "America"]},
            {"name": "Germany", "aliases": []},
            {"name": "India", "aliases": []},
            {"name": "Brazil", "aliases": []},
            {"name": "Spain", "aliases": []},
            {"name": "France", "aliases": []},
            {"name": "Canada", "aliases": []},
            {"name": "Sweden", "aliases": []},
            {"name": "Australia", "aliases": []},
        ],
        "sources": [
            {
                "title": "Wikipedia — Wind power by country (total wind capacity)",
                "url": "https://en.wikipedia.org/wiki/Wind_power_by_country",
            },
            {
                "title": "Wikipedia — Offshore wind power by country (offshore capacity)",
                "url": "https://en.wikipedia.org/wiki/Offshore_wind_power",
            }
        ],
        "source_note": "This ranking is derived from total wind capacity minus offshore capacity using 2024 published country tables. Because the public tables are rounded, places near the bottom are approximate."
    },
    {
        "id": 16,
        "title": "Top 10 countries with solar capacity",
        "aliases": [
            "solar capacity",
            "countries with solar capacity",
            "solar countries",
            "top solar countries",
        ],
        "ranking_note": "Installed solar power capacity.",
        "answers": [
            {"name": "China", "aliases": []},
            {"name": "United States", "aliases": ["USA", "US", "United States of America", "America"]},
            {"name": "India", "aliases": []},
            {"name": "Japan", "aliases": []},
            {"name": "Brazil", "aliases": []},
            {"name": "Germany", "aliases": []},
            {"name": "Spain", "aliases": []},
            {"name": "Australia", "aliases": []},
            {"name": "Italy", "aliases": []},
            {"name": "South Korea", "aliases": ["Korea", "Republic of Korea"]},
        ],
        "sources": [
            {
                "title": "Wikipedia — Solar power by country",
                "url": "https://en.wikipedia.org/wiki/Solar_power_by_country",
            }
        ],
        "source_note": "This game uses the 2024 capacity table."
    },
    {
        "id": 17,
        "title": "Top 10 countries with renewable share",
        "aliases": [
            "renewable share",
            "countries with renewable share",
            "most renewable electricity",
            "renewable electricity share",
            "renewables share",
        ],
        "ranking_note": "Renewable share of electricity generation, not total energy use.",
        "answers": [
            {"name": "Albania", "aliases": []},
            {"name": "Bhutan", "aliases": []},
            {"name": "Central African Republic", "aliases": ["CAR"]},
            {"name": "DR Congo", "aliases": ["Democratic Republic of the Congo", "Democratic Republic of Congo", "DRC", "Congo-Kinshasa"]},
            {"name": "Ethiopia", "aliases": []},
            {"name": "Iceland", "aliases": []},
            {"name": "Lesotho", "aliases": []},
            {"name": "Nepal", "aliases": []},
            {"name": "Paraguay", "aliases": []},
            {"name": "Norway", "aliases": []},
        ],
        "sources": [
            {
                "title": "Wikipedia — List of countries by renewable electricity production",
                "url": "https://en.wikipedia.org/wiki/List_of_countries_by_renewable_electricity_production",
            }
        ],
        "source_note": "This category uses renewable electricity share, not overall energy consumption. Several countries are tied at 100%, so for gameplay they are ordered alphabetically before Norway at 99%."
    },
    {
        "id": 18,
        "title": "Top 10 most spoken languages in the world",
        "aliases": [
            "most spoken languages",
            "languages by total speakers",
            "top languages",
            "spoken languages",
        ],
        "ranking_note": "All speakers (L1 + L2), not native speakers only.",
        "answers": [
            {"name": "English", "aliases": []},
            {"name": "Mandarin Chinese", "aliases": ["Mandarin", "Chinese"]},
            {"name": "Hindi", "aliases": []},
            {"name": "Spanish", "aliases": []},
            {"name": "Modern Standard Arabic", "aliases": ["Arabic"]},
            {"name": "French", "aliases": []},
            {"name": "Bengali", "aliases": ["Bangla"]},
            {"name": "Portuguese", "aliases": []},
            {"name": "Indonesian", "aliases": ["Bahasa Indonesia"]},
            {"name": "Urdu", "aliases": []},
        ],
        "sources": [
            {
                "title": "Wikipedia — List of languages by total number of speakers (Ethnologue 2026 table)",
                "url": "https://en.wikipedia.org/wiki/List_of_languages_by_total_number_of_speakers",
            }
        ],
        "source_note": "This game uses the Ethnologue 2026 total-speaker table (L1 + L2). The page notes that language ranking depends on source definitions and excludes some macrolanguages."
    },
    {
        "id": 19,
        "title": "Top 10 most watched sports globally",
        "aliases": [
            "most famous sports",
            "most watched sports",
            "sports by viewers",
            "sports popularity",
            "sports viewers",
        ],
        "ranking_note": "Estimated global viewership.",
        "answers": [
            {"name": "Football (soccer)", "aliases": ["Football", "Soccer", "Association Football"]},
            {"name": "Cricket", "aliases": []},
            {"name": "Hockey", "aliases": []},
            {"name": "Tennis", "aliases": []},
            {"name": "Volleyball", "aliases": []},
            {"name": "Table Tennis", "aliases": ["Ping Pong", "Ping-Pong"]},
            {"name": "Basketball", "aliases": []},
            {"name": "Baseball", "aliases": []},
            {"name": "Rugby", "aliases": []},
            {"name": "Golf", "aliases": []},
        ],
        "sources": [
            {
                "title": "Limelight Digital — Most Watched Sports in the World (viewership stats)",
                "url": "https://www.limelightdigital.co.uk/sports-viewership-statistics/",
            }
        ],
        "source_note": "This category is based on estimated global viewership from a secondary source, so it is less definitive than the more statistical country tables used elsewhere in the game."
    },
    {
        "id": 20,
        "title": "Top 10 movies of all time based on IMDb",
        "aliases": [
            "top imdb movies",
            "imdb top 10",
            "best movies imdb",
            "movies imdb",
            "imdb movies",
        ],
        "ranking_note": "IMDb Top 250 snapshot.",
        "answers": [
            {"name": "The Shawshank Redemption", "aliases": ["Shawshank Redemption"]},
            {"name": "The Godfather", "aliases": ["Godfather"]},
            {"name": "The Dark Knight", "aliases": ["Dark Knight"]},
            {"name": "The Godfather: Part II", "aliases": ["Godfather 2", "The Godfather Part II", "Godfather Part 2"]},
            {"name": "12 Angry Men", "aliases": ["Twelve Angry Men"]},
            {"name": "The Lord of the Rings: The Return of the King", "aliases": ["Return of the King", "LOTR Return of the King", "Lord of the Rings Return of the King"]},
            {"name": "Schindler's List", "aliases": ["Schindlers List"]},
            {"name": "The Lord of the Rings: The Fellowship of the Ring", "aliases": ["Fellowship of the Ring", "LOTR Fellowship of the Ring", "Lord of the Rings Fellowship of the Ring"]},
            {"name": "Pulp Fiction", "aliases": []},
            {"name": "The Good, the Bad and the Ugly", "aliases": ["The Good The Bad and The Ugly", "Good Bad and Ugly", "Good the Bad and the Ugly"]},
        ],
        "sources": [
            {
                "title": "IMDb — Top 250 Movies",
                "url": "https://www.imdb.com/chart/top/",
            },
            {
                "title": "List Challenges — IMDb Top 250 Movies of All Time (2026 update) snapshot",
                "url": "https://www.listchallenges.com/imdb2026",
            }
        ],
        "source_note": "IMDb rankings change over time. This game uses a fixed snapshot of the top 10 from early 2026."
    },
]


def build_category_index() -> Dict[int, Dict]:
    return {category["id"]: category for category in CATEGORIES}


CATEGORY_BY_ID = build_category_index()


def category_lookup(user_input: str) -> Optional[Dict]:
    cleaned = normalize(user_input)

    if not cleaned:
        return None

    if cleaned.isdigit():
        category_id = int(cleaned)
        return CATEGORY_BY_ID.get(category_id)

    exact_matches = []
    for category in CATEGORIES:
        possible_names = [category["title"], *category["aliases"]]
        normalized_names = {normalize(name) for name in possible_names}
        if cleaned in normalized_names:
            exact_matches.append(category)

    if len(exact_matches) == 1:
        return exact_matches[0]

    partial_matches = []
    for category in CATEGORIES:
        possible_names = [category["title"], *category["aliases"]]
        normalized_names = [normalize(name) for name in possible_names]
        if any(cleaned in name or name in cleaned for name in normalized_names):
            partial_matches.append(category)

    if len(partial_matches) == 1:
        return partial_matches[0]

    return None


def render_board(category: Dict, found_indices: Set[int]) -> str:
    lines = []
    for index, answer in enumerate(category["answers"], start=1):
        value = answer["name"] if index in found_indices else "....."
        lines.append(f"{index}. {value}")
    return "\n".join(lines)


def answer_matches(guess: str, answer: Dict) -> bool:
    guess_norm = normalize(guess)
    accepted = {normalize(answer["name"])}
    accepted.update(normalize(alias) for alias in answer.get("aliases", []))
    return guess_norm in accepted


def find_correct_answer(guess: str, category: Dict, found_indices: Set[int]) -> Optional[int]:
    for index, answer in enumerate(category["answers"], start=1):
        if index in found_indices:
            continue
        if answer_matches(guess, answer):
            return index
    return None


def is_already_found(guess: str, category: Dict, found_indices: Set[int]) -> bool:
    for index, answer in enumerate(category["answers"], start=1):
        if index not in found_indices:
            continue
        if answer_matches(guess, answer):
            return True
    return False


def print_intro() -> None:
    print("=" * 72)
    print("WELCOME TO THE TOP 10 GUESSING GAME")
    print("=" * 72)
    print("How the game works:")
    print("- Pick one category.")
    print("- The game loads a hidden Top 10 list for that category.")
    print("- You guess one answer at a time.")
    print("- If your answer is correct, it appears in its real rank.")
    print("- You have 3 lives.")
    print("- After 3 wrong answers, the round is over.")
    print("- After the round, you can play again or reveal the full list and sources.")
    print("=" * 72)
    print()


def print_categories() -> None:
    print("Available categories:")
    for category in CATEGORIES:
        print(f"{category['id']:>2}. {category['title']}")
    print()


def choose_category() -> Dict:
    while True:
        print_categories()
        choice = input("Choose a category by number or by name: ").strip()
        category = category_lookup(choice)

        if category:
            return category

        print("I could not find that category. Please try again.\n")


def show_full_list_and_sources(category: Dict) -> None:
    print("\n" + "=" * 72)
    print(f"FULL LIST — {category['title'].upper()}")
    print("=" * 72)
    for index, answer in enumerate(category["answers"], start=1):
        print(f"{index}. {answer['name']}")

    print("\nSource note:")
    print(category["source_note"])

    print("\nSources:")
    for source in category["sources"]:
        print(f"- {source['title']}")
        print(f"  {source['url']}")
    print("=" * 72 + "\n")


def play_round(category: Dict) -> None:
    print("\n" + "=" * 72)
    print(f"CATEGORY: {category['title']}")
    print("=" * 72)
    print(f"Ranking basis: {category['ranking_note']}")
    print(f"Lives: {MAX_LIVES}")
    print()
    print(render_board(category, set()))

    lives = MAX_LIVES
    found_indices: Set[int] = set()
    first_turn = True

    while lives > 0 and len(found_indices) < 10:
        prompt = "\nGive me your first answer: " if first_turn else "\nNext answer: "
        guess = input(prompt).strip()

        if not guess:
            print("Please type an answer.")
            continue

        if normalize(guess) in {"quit", "exit"}:
            print("\nRound ended early.")
            break

        if is_already_found(guess, category, found_indices):
            print("You already found that answer. Try another one.")
            continue

        correct_index = find_correct_answer(guess, category, found_indices)

        if correct_index is not None:
            found_indices.add(correct_index)
            correct_name = category["answers"][correct_index - 1]["name"]
            print(f"\nCorrect! #{correct_index} is {correct_name}.")
        else:
            lives -= 1
            if lives > 0:
                print(f"\nWrong answer. Lives left: {lives}")
            else:
                print("\nWrong answer. That was your last life.")

        print()
        print(render_board(category, found_indices))
        first_turn = False

    if len(found_indices) == 10:
        print("\nAmazing! You found all 10 answers.")
    elif lives == 0:
        print("\nYou lost. Game over.")

    while True:
        print("\nWhat do you want to do now?")
        print("1. Play again")
        print("2. Show the full list + sources")
        print("3. Quit")
        after_round = input("Choose 1, 2, or 3: ").strip()

        if after_round == "1":
            print()
            return "again"

        if after_round == "2":
            show_full_list_and_sources(category)
            while True:
                next_step = input("Type 1 to play again or 2 to quit: ").strip()
                if next_step == "1":
                    print()
                    return "again"
                if next_step == "2":
                    print("Thanks for playing!")
                    return "quit"
                print("Please choose 1 or 2.")

        if after_round == "3":
            print("Thanks for playing!")
            return "quit"

        print("Please choose 1, 2, or 3.")


def main() -> None:
    print_intro()

    while True:
        category = choose_category()
        action = play_round(category)
        if action == "quit":
            break


if __name__ == "__main__":
    main()